- charts/waterfallchart/api-specifications/api.md
- charts/waterfallchart/api-specifications/properties.json
- charts/waterfallchart/src/object-properties.js
> fix(waterfall): fix default props

- charts/boxplot/src/boxplot-view.js
- charts/distributionplot/src/distributionplot-view.js
- charts/histogram/src/chart-settings/chart-settings.js
- charts/histogram/src/histogram-view.js
- charts/waterfallchart/src/waterfallchart-view.js
the supernova api have no support to differentiate between scoll is temporary of permanent disabled
fix #5
> fix: treat no scroll as temporary off

- charts/histogram/src/__tests__/histogram-export.spec.js
- charts/histogram/src/ext.js
- charts/histogram/src/histogram-export.js
- jest.config.js
> feat: enable custom histogram export

- charts/distributionplot/api-specifications/api.md
- charts/distributionplot/api-specifications/properties.json
- charts/distributionplot/src/object-properties.js
> fix: distplot default sort

- chart-modules/common/picasso/tooltip/tooltip-content.js
- charts/distributionplot/src/distributionplot-view.js
> fix: color in distplot tooltip

- chart-modules/common/picasso/scroll/scroll-handler.js
- charts/distributionplot/src/distributionplot-view.js
> fix: scroll in legend (tap, pan, wheel)

- charts/distributionplot/src/distributionplot-view.js
> fix: color legend display order

- chart-modules/common/extra/backend-api/snapshot-api.js
- charts/boxplot/src/boxplot-backend-api.js
- charts/boxplot/src/boxplot-view.js
- charts/boxplot/src/index.js
- charts/distributionplot/src/distributionplot-view.js
- charts/distributionplot/src/index.js
- charts/histogram/src/backend-api.js
- charts/histogram/src/histogram-view.js
- charts/waterfallchart/src/waterfallchart-view.js
> fix: no data fetch or scrollbar in snapshot

- chart-modules/common/picasso/scroll/scroll-handler.js
> fix: do preventDefault on the correct object

- chart-modules/common/extra/__tests__/hard-properties-checker.spec.js
- chart-modules/common/extra/hard-properties-checker.js
- chart-modules/common/picasso/derived-properties/derived-properties.js
- chart-modules/common/picasso/derived-properties/save/save.js
> fix: setPropertes of applyPatches

- chart-modules/common/nebula/snapshot.js
- charts/distributionplot/package.json
- yarn.lock
> Fix wait on snapshot

- chart-modules/common/picasso/selections/selections-handler.js
> fix: reset lasso on deselect

- .circleci/config.yml
> chore: remove approve step

- charts/waterfallchart/src/ext.js
> fix(waterfall): add missing return to fix export

- charts/waterfallchart/package.json
- charts/waterfallchart/src/__tests__/waterfallchart-tick-generator.spec.js
- charts/waterfallchart/src/waterfallchart-tick-generator.js
- charts/waterfallchart/src/waterfallchart-view.js
- yarn.lock
Fix: https://jira.qlikdev.com/browse/QB-6590
> fix(waterfall-chart): show set min and set max as ticks

- chart-modules/common/picasso/chart-view.js
> test: add picasso-chart class

- chart-modules/common/picasso/disclaimer/disclaimer-attributes-util.js
- charts/histogram/src/__tests__/histogram-view.spec.js
- charts/histogram/src/histogram-view.js
Without this fix it also show for some/all cases when there is no dimension values
> fix(histogram): correct require numeric dimension discalimer

- .circleci/api-gov.sh
- .circleci/config.yml
Hello!
We are migrating to a new image for doing API compliance.
Check that the paths and names are correct to your repo.
If you have any questions don't hesitate to reach out.
> chore: update api compliance

- charts/boxplot/src/boxplot-cubes-generator.js
Fixes https://jira.qlikdev.com/browse/QB-8996
> fix(boxplot): safeguard against missing sort criterias

- charts/distributionplot/src/distributionplot-import-export.js
This is a short term fix for distribution plot conversion.
> fix: fix conversion

- chart-modules/common/locale/all.json
- charts/distributionplot/src/__tests__/distributionplot-properties.spec.js
- charts/distributionplot/src/distributionplot-properties.js
https://user-images.githubusercontent.com/25456307/168547228-086e605c-0714-4e5d-a605-54af94323382.mov
> feat(distplot): add property in axis simple mode

- charts/waterfallchart/src/waterfallchart-properties.js
Before fixing in simple mode
After fixing:
> feat: add correct measure title in simple mode

- charts/boxplot/package.json
- charts/boxplot/src/boxplot-import-export.js
- charts/distributionplot/package.json
- charts/histogram/package.json
- charts/waterfallchart/package.json
- yarn.lock
This PR depends on https://github.com/qlik-trial/conversion/pull/68 changes.
> fix: set isHCModifierSupported to false to prevent unquarantineProperty (qDynamicScripts) for box-plot

- charts/waterfallchart/src/waterfallchart-properties.js
To support this PR: https://github.com/qlik-trial/analytics/pull/228
> fix(analytic-creation): default value for waterfall data point labels

- charts/boxplot/src/boxplot-properties.js
- charts/boxplot/src/styling-panel-definition.js
This PR is to enable the new styling panel and Background options (IM-323) in Boxplot.
> feat(box-plot): enabled new styling panel

- charts/histogram/src/histogram-properties.js
- charts/histogram/src/styling-panel-definition.js
This PR is to enable the new styling panel and Background options (IM-323) in Histogram.
> feat(histogram): enabled new styling panel

- charts/boxplot/src/boxplot-properties.js
- charts/distributionplot/src/distributionplot-properties.js
- charts/waterfallchart/src/waterfallchart-properties.js
Fixed the background options feature flag for waterfall chart, dist-plot and box plot to include IM numbers.
> fix: change chart background feature flags

- charts/histogram/src/histogram-properties.js
This PR changes the feature flag to enable background options of Histogram to include the IM number
> fix(histogram): change background options feature flag

- .circleci/config.yml
- charts/boxplot/package.json
- charts/distributionplot/package.json
- charts/histogram/package.json
- charts/waterfallchart/package.json
Adds build and publish of sense ext stuff.
> chore: add ext build

- chart-modules/common/extra/__tests__/chart-style-component.spec.js
- chart-modules/common/extra/chart-style-component.js
- chart-modules/common/picasso/chart-builder/presets/dimension-measure-chart/__tests__/dimension-measure-chart.spec.js
- chart-modules/common/picasso/chart-builder/presets/dimension-measure-chart/dimension-measure-chart.js
- charts/boxplot/package.json
- charts/boxplot/src/__tests__/boxplot-view.spec.js
- charts/boxplot/src/boxplot-properties.js
- charts/boxplot/src/boxplot-view.js
- charts/boxplot/src/styling-panel-definition.js
- charts/distributionplot/package.json
- charts/distributionplot/src/__tests__/distributionplot-view.spec.js
- charts/distributionplot/src/distributionplot-properties.js
- charts/distributionplot/src/distributionplot-view.js
- charts/distributionplot/src/styling-panel-definition.js
- charts/histogram/package.json
- charts/histogram/src/chart-settings/__tests__/chart-settings.spec.js
- charts/histogram/src/chart-settings/chart-settings.js
- charts/histogram/src/chart-settings/label.js
- charts/histogram/src/histogram-properties.js
- charts/histogram/src/histogram-view.js
- charts/histogram/src/index.js
- charts/histogram/src/styling-panel-definition.js
- charts/waterfallchart/package.json
- charts/waterfallchart/src/__tests__/waterfallchart-properties.spec.js
- charts/waterfallchart/src/__tests__/waterfallchart-view.spec.js
- charts/waterfallchart/src/index.js
- charts/waterfallchart/src/styling-panel-property-definiton.js
- charts/waterfallchart/src/waterfallchart-properties.js
- charts/waterfallchart/src/waterfallchart-view.js
- yarn.lock
The following stying (Font label, font colour and font size) options have been added
- Axis label
- Axis title
- Value label
for the following charts
- Histogram
- Waterfall
- Distplot
- Boxplot
- Gauge
Jira: https://jira.qlikdev.com/browse/IM-3364
> feat: added styling for different charts IM-3364

- charts/boxplot/src/boxplot-properties.js
- charts/distributionplot/src/distributionplot-properties.js
- charts/histogram/src/histogram-properties.js
- charts/waterfallchart/src/waterfallchart-properties.js
Correcting the key for styling panel
> fix(IM-6456): use default styling panel
